# Generated by Django 3.0.7 on 2021-04-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminhod_parents_sessionyearmodel_staff_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminhod',
            options={'verbose_name_plural': 'Admin(HOD)'},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='sessionyearmodel',
            options={'verbose_name_plural': 'Session year'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='adminhod',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='admin',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='admin',
            new_name='user',
        ),
    ]
