# Generated by Django 3.0.7 on 2021-05-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_feedbackparent_notificationparent'),
        ('accounts', '0003_auto_20210426_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
    ]
