# Generated by Django 3.0.7 on 2021-05-02 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210502_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.SessionYearModel'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
