# Generated by Django 3.0.7 on 2021-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210516_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Parent')], default=1, max_length=10),
        ),
    ]
