# Generated by Django 3.0.7 on 2021-05-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210517_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='parent_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Students'),
        ),
    ]
