# Generated by Django 3.2 on 2021-05-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_first_name'),
        ('accounts', '0012_parents_parent_of'),
    ]

    operations = [
    ]
