# Generated by Django 3.2 on 2021-06-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fcm_token',
        ),
    ]
