# Generated by Django 3.2 on 2021-07-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['session_year_id']},
        ),
    ]
