# Generated by Django 3.0.7 on 2021-07-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210713_1340'),
        ('accounts', '0023_alter_courses_options'),
    ]

    operations = [
    ]
