# Generated by Django 3.0.7 on 2021-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20210713_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='ph_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
