# Generated by Django 3.0.7 on 2021-07-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210713_2023'),
        ('accounts', '0025_alter_customuser_first_name'),
    ]

    operations = [
    ]
