# Generated by Django 3.0.7 on 2021-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
