# Generated by Django 3.0.7 on 2021-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210527_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
