# Generated by Django 3.0.7 on 2021-05-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_auto_20210516_1545'),
        ('assignments', '0002_message_notification_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='student_management.Subjects'),
        ),
    ]
