# Generated by Django 3.2 on 2021-05-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20210516_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='course',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='course',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='course',
            new_name='subject',
        ),
    ]
