# Generated by Django 3.0.7 on 2021-06-08 09:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assignment',
            name='text_assignment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
