# Generated by Django 3.0.7 on 2021-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20210608_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='link',
        ),
    ]
