# Generated by Django 3.0.8 on 2021-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_auto_20210608_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
