# Generated by Django 3.0.7 on 2021-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_quiz_quizanswers_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_for_quiz',
            field=models.DurationField(null=True),
        ),
    ]
