# Generated by Django 3.0.7 on 2021-06-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_auto_20210610_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.Quiz'),
        ),
    ]
