# Generated by Django 3.0.7 on 2021-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_quizchoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizchoice',
            options={},
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='choice1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='choice2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='choice3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='choice4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizchoice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quizchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='quizchoice',
            name='position',
        ),
    ]
