# Generated by Django 3.0.7 on 2021-06-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_auto_20210611_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizchoice',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.QuizQuestions'),
        ),
    ]
