# Generated by Django 3.0.7 on 2021-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_auto_20210611_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
