# Generated by Django 3.2 on 2021-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_remove_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_status',
            field=models.BooleanField(default=False),
        ),
    ]
