# Generated by Django 3.2 on 2021-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_submission_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
