# Generated by Django 3.0.7 on 2021-05-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210516_1545'),
        ('student_management', '0003_feedbackparent_notificationparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Courses'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
