# Generated by Django 3.0.8 on 2021-06-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210604_1843'),
        ('student_management', '0005_subjects_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Students'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management.Subjects'),
        ),
    ]
