# Generated by Django 3.0.8 on 2021-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210604_1843'),
        ('student_management', '0008_auto_20210606_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='student_id',
            field=models.ManyToManyField(related_name='student', to='accounts.Students'),
        ),
    ]
