# Generated by Django 3.0.7 on 2021-06-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210604_1843'),
        ('student_management', '0009_auto_20210606_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='accounts.Staffs'),
        ),
    ]
