# Generated by Django 3.0.7 on 2021-06-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_auto_20210607_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
    ]
