# Generated by Django 3.0.7 on 2021-06-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_remove_attendance_session_year_id'),
        ('student_management', '0011_subjects_session_year_id'),
    ]

    operations = [
    ]
